config/routes.rb
AngularRailsHacking::Application.routes.draw do

  # using devise for demo
  devise_for :users

  # root
  root :to => 'home#index'

  # user root is the dashboard
  match 'dashboard' => 'dashboard#index', :as => :user_root

  # the photo album is a single page app in angular so this route matches the angular route back to the start of the photo albums single page
  match '/user/:user_id/album/:album_id/photos' => 'users/albums#index'

  # bunch of normal resources
  resources :users do
    resources :albums, module: :users do
      resources :photos
    end
  end
end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :user
  attr_accessible :name
  has_many :photos, dependent: :destroy
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :album
  attr_accessible :title


  attr_accessible :image
  has_attached_file :image, 
                    :styles => { :medium => "300x300>", :thumb => "100x100>" },
                    :default_url => "/assets/:style/missing.png"


  def thumbnail_url
    image.url(:thumb)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name

  has_many :albums
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!

  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users/albums_controller.rb
class Users::AlbumsController < ApplicationController
  before_filter :authenticate_user!

  respond_to :json, :html

  def show
    @user = User.find(params[:user_id])
    @album = @user.albums.find(params[:id])

    respond_with(@album) do |format|
      format.html { render }
      format.json { render json: @album.to_json }
    end
  end

  def index
    @user = User.find(params[:user_id])
    @albums = @user.albums

    respond_with(@albums) do |format|
      format.html { render }
      format.json { render json: @albums.to_json(root: false) }
    end
  end

  def create
    @user = User.find(params[:user_id])
    @album = @user.albums.create(params[:album])

    respond_with(@album) do |format|
      format.html { render }
      format.json { render json: @album.to_json(root: false) }
    end
  end

  def update
    @user = User.find(params[:user_id])
    @album = @user.albums.find(params[:id])
    @album.update_attributes(params[:album])

    respond_with(@album) do |format|
      format.html { render }
      format.json { render json: @album.to_json(root: false) }
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @album = @user.albums.find(params[:id])
    @album.delete

    respond_with(@album) do |format|
      format.html { render }
      format.json { render json: @album.to_json(root: false) }
    end
  end
end

app/controllers/users/photos_controller.rb
class Users::PhotosController < ApplicationController
  before_filter :authenticate_user!

  respond_to :json

  def index
    @user   = User.find(params[:user_id])
    @album  = @user.albums.find(params[:album_id])
    @photos = @album.photos.page(params[:page] || 1)

    respond_with(@photos) do |format|
      format.html { render }
      format.json { render json: @photos.to_json(methods: :thumbnail_url) }
    end
  end

  def create
    user   = User.find(params[:user_id])
    album  = user.albums.find(params[:album_id])
  
    photos_uploaded = []

    params[:files].each do |file|
      photos_uploaded << album.photos.create(title: file.original_filename, image: file)
    end

    respond_with(photos_uploaded) do |format|
      format.json { render json: photos_uploaded.to_json(root: false) }
    end
  end

  def update
    user   = User.find(params[:user_id])
    album  = user.albums.find(params[:album_id])
    photo  = album.photos.find(params[:id])
    photo.update_attributes(params[:photo])

    respond_with(photo) do |format|
      format.json { render json: photo.to_json(root: false) }
    end
  end

  def destroy
    user   = User.find(params[:user_id])
    album  = user.albums.find(params[:album_id])
    photo  = album.photos.find(params[:id])
    photo.delete

    respond_with(photo) do |format|
      format.json { render json: photo.to_json(root: false) }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users/albums_helper.rb
module Users::AlbumsHelper
end

app/helpers/users/photos_helper.rb
module Users::PhotosHelper
end

app/views/dashboard/index.html.haml
%h2 Dashboard for #{current_user.name}

%p
  Please go to My Albums

=link_to "My Albums", user_albums_path(current_user), :class => 'btn'

app/views/home/index.html.haml
%p
  -if user_signed_in?
    You are signed in as #{current_user.email}
  -else
    Please sign in with fred@example.com/password

app/views/layouts/application.html.haml
%html
  %head
    %title AngularRailsHacking
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .navbar.navbar-inverse.navbar-fixed-top
      .navbar-inner
        .container
          %button.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse", :type => "button"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{:href => "/"} Angularjs Rails Hacking
          .nav-collapse.collapse
            %ul.nav
              - if user_signed_in?
                %li
                  =link_to "Dashboard", user_root_path
                %li
                  =link_to 'Sign Out', destroy_user_session_path, method: :delete if user_signed_in?
              - else
                %li
                  =link_to "Sign Up", new_user_registration_path
                %li
                  =link_to "Sign In", new_user_session_path

            - unless user_signed_in?
              = form_for(:user, :as => :user, :url => session_path(:user), :html => {:class => "navbar-form pull-right"}) do |f|
                = f.email_field :email, :autofocus => true, :placeholder => "Email", :class => "span2"
                = f.password_field :password, :placeholder => "Password", :class => "span2"
                = f.submit "Sign in", :class => "btn"
  
    .container-fluid
      = yield

app/views/users/albums/index.html.haml
%div{'ng-app' => 'MyApp'}
  %div{'ng-view' => 'ng-view'}

app/views/users/photos/index.html.haml
%h1 Users::Photos#index
%p Find me in app/views/users/photos/index.html.haml